# This creates a discovery LB for each member in the core set, and ties to 
# the use of the Neo4j discovery type "K8S" with the configured selectors.
{{- $dot := . }}
{{- $times := int .Values.core.numberOfServers }}
{{- range untilStep 0 $times 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-{{ template "neo4j.fullname" $dot }}-{{ . }}
  labels:
    neo4j.com/cluster: {{ template "neo4j.fullname" $dot }}
    neo4j.com/role: CORE
    app.kubernetes.io/managed-by: {{ $dot.Release.Service | quote }}
    app.kubernetes.io/instance: {{ $dot.Release.Name | quote }}
    helm.sh/chart: "{{ $dot.Chart.Name }}-{{ $dot.Chart.Version }}"
    app.kubernetes.io/name: {{ template "neo4j.name" $dot }}
    app.kubernetes.io/component: core
spec:
  publishNotReadyAddresses: true
  type: LoadBalancer
  ports:
    - name: discovery
      port: 5000
      targetPort: 5000
      protocol: TCP
    - name: transaction
      port: 6000
      targetPort: 6000
      protocol: TCP
    - name: raft
      port: 7000
      targetPort: 7000
      protocol: TCP
    {{- if .Values.metrics.prometheus.enabled }}
    - containerPort: 2004
      name: prometheus
    {{- end }}
    {{- if .Values.metrics.graphite.enabled }}
    - containerPort: 2003
      name: graphite
    {{- end }}
    {{- if .Values.metrics.jmx.enabled }}
    - containerPort: 3637
      name: jmx
    {{- end }}
  selector:
    statefulset.kubernetes.io/pod-name: "{{ template "neo4j.fullname" $dot }}-core-{{ . }}"
{{- end }}    