# Sample pod to be applied manually or scheduled when desired
# Executes a backup against the DB when tailored to the right endpoint.
# Copies resulting full backup to $BUCKET
apiVersion: v1
kind: Pod
metadata:
  name: neo4j-backup
spec:
  restartPolicy: Never
  containers:
    - name: neo4j-backup
      image: gcr.io/neo4j-helm/backup:4.0.5-1
      env:
      - name: NEO4J_ADDR
        value: "a-neo4j.default.svc.cluster.local"
      - name: BUCKET
        value: gs://graph-backup-storage
      - name: DATABASE
        value: neo4j
      - name: BACKUP_NAME
        value: neo4j
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /auth/credentials.json
      volumeMounts:
      - name: creds
        mountPath: /auth
        readOnly: true
  volumes:
  - name: creds
    secret:
      secretName: neo4j-service-key
      items:
      - key: credentials.json
        path: credentials.json
